// Authentification
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = "LOGOUT_USER";


// Oranizations
export const LOAD_ORGANIZATIONS = 'LOAD_ORGANIZATIONS';
export const ADD_ORGANIZATION = 'ADD_ORGANIZATION';
export const UPDATE_ORGANIZATION = 'UPDATE_ORGANIZATION';
export const DELETE_ORGANIZATION = 'DELETE_ORGANIZATION';
export const GET_ORGANIZATION_BY_VILLAGE = 'GET_ORGANIZATION_BY_VILLAGE';
export const GET_ORGANIZATION_BY_CITY = 'GET_ORGANIZATION_BY_CITY';
export const ADD_ORGANIZATION_TO_PLACE = 'ADD_ORGANIZATION_TO_PLACE';
export const ADD_SERVICES_TO_ORGANIZATION = 'ADD_SERVICES_TO_ORGANIZATION';
export const LOAD_ADDED_SERVICES_TO_ORGANIZATION = 'LOAD_ADDED_SERVICES_TO_ORGANIZATION';
export const DELETE_SERVICES_FROM_ORGANIZATION = 'DELETE_SERVICES_FROM_ORGANIZATION';

export const LOAD_EMPLOYEES_OF_ORGANIZATION = 'LOAD_EMPLOYEES_OF_ORGANIZATION';
export const ADD_EMPLOYEE_TO_ORGANIZATION = 'ADD_EMPLOYEE_TO_ORGANIZATION';
export const DELETE_EMPLOYEE_FROM_ORGANIZATION = 'DELETE_EMPLOYEE_FROM_ORGANIZATION';
export const UPDATE_EMPLOYEE_OF_ORGANIZATION = 'UPDATE_EMPLOYEE_OF_ORGANIZATION';
export const GET_EMPLOYEES_BY_ORG_ID = 'GET_EMPLOYEES_BY_ORG_ID';

export const CREATE_TIMETABLE_FOR_EMPLOYEE = 'CREATE_TIMETABLE_FOR_EMPLOYEE';
export const GET_TIMETABLE_BY_ORG_ID = 'GET_TIMETABLE_BY_ORG_ID';
export const DELETE_TIMETABLE_BY_ID = 'DELETE_TIMETABLE_BY_ID';
export const UPDATE_TIMETABLE_BY_ID = 'UPDATE_TIMETABLE_BY_ID';
export const GET_TIMETABLE_REQUEST = 'GET_TIMETABLE_REQUEST';
export const UPDATE_TIMETABLE_REQUEST = 'UPDATE_TIMETABLE_REQUEST';

// Kids group
export const GET_KIDS_GROUP = 'GET_KIDS_GROUP';
export const ADD_GROUP_TO_KIDS_AGE_GROUP = 'ADD_GROUP_TO_KIDS_AGE_GROUP';
export const DELETE_GROUP_FROM_KIDS_AGE_GROUP = 'DELETE_GROUP_FROM_KIDS_AGE_GROUP';
export const UPDATE_GROUP_OF_KIDS_AGE_GROUP = 'UPDATE_GROUP_OF_KIDS_AGE_GROUP';
export const GET_KIDS_GROUPS_BY_KIDS_AGE_ID = 'GET_KIDS_GROUPS_BY_KIDS_AGE_ID';

// Users by role
export const LOAD_USERS_BY_ROLE = 'LOAD_USERS_BY_ROLE';
export const UPDATE_USERS_BY_ROLE = 'UPDATE_USERS_BY_ROLE';
export const ADD_USERS_BY_ROLE = 'ADD_USERS_BY_ROLE';
export const DELETE_USERS_BY_ROLE = 'DELETE_USERS_BY_ROLE';
export const GET_USERS_BY_ORGANZIATION_ID = 'GET_USERS_BY_ORGANZIATION_ID';


// Services
export const LOAD_SERVICES = 'LOAD_SERVICES';
export const ADD_SERVICE = 'ADD_SERVICE';
export const DELETE_SERVICE = 'DELETE_SERVICE';
export const UPDATE_SERVICE = 'UPDATE_SERVICE';
export const GET_KIDS_AGE_GROUP = 'GET_KIDS_AGE_GROUP';

export const GET_WORKERS_TRANSPORT_REQUESTS = 'GET_WORKERS_TRANSPORT_REQUESTS';

// Regions
export const LOAD_REGIONS = 'LOAD_REGIONS';
export const ADD_REGION = 'ADD_REGION';
export const DELETE_REGION = 'DELETE_REGION';
export const UPDATE_REGION = 'UPDATE_REGION';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';

// utilsState
// utils states are state that do not belong to a particular category
export const ENABLE_ADD_DIALOG_BUTTON = 'ENABLE_ADD_DIALOG_BUTTON';
export const CLEAR_ORGANIZATION_BY_PLACE = 'CLEAR_ORGANIZATION_BY_PLACE';
export const GET_EGOV_SERVICE_LIST = 'GET_EGOV_SERVICE_LIST';
export const GET_ROLES = 'GET_ROLES';
export const FILTER_USERS_BY_ROLE = 'FILTER_USERS_BY_ROLE'

// alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Languages
export const GET_LANGUAGES = 'GET_LANGUAGES';


